#
# GNUmakefile - Generated by ProjectCenter
# Written by Philippe C.D. Robert <phr@3dkit.org>
#
# NOTE: Do NOT change this file -- ProjectCenter maintains it!
#
# Put all of your customisations in GNUmakefile.preamble and
# GNUmakefile.postamble
#

include $(GNUSTEP_MAKEFILES)/common.make

DOCUMENT_NAME=BurnDoc

BurnDoc_AGSDOC_FILES =\
Burn.gsdoc \
Project.h \
Functions.h \
ConsolePanel.h \
OpenISOImagePanel.h \
Burn/ExternalTools.h \
Burn/PreferencesModule.h

#
# Subprojects
#
SUBPROJECTS = 

ifneq ($(bundles),no)
  SUBPROJECTS += \
    Bundles/CDrecord \
    Bundles/CDparanoia \
    Bundles/MP3ToWav \
    Bundles/Cdrdao \
    Bundles/MkIsoFs
endif


#
# Main application
#

PACKAGE_NAME=Burn
APP_NAME=Burn
Burn_APPLICATION_ICON=iconGSburn.tiff


#
# Additional libraries
#

ADDITIONAL_GUI_LIBS += 

#
# Resource files
#

Burn_RESOURCE_FILES= \
Burn.help \
Images/iconGSburn.tiff \
Images/iconDelete.tiff \
Images/iconAudioCD.tiff \
Images/iconBurn.tiff \
Images/iconBurnIso.tiff \
Images/iconCreateIso.tiff \
Images/iconBlankCD.tiff \
Images/iconDnD.tiff \
Images/iconDnDMulti.tiff \
Images/iconDnDAudio.tiff \
Images/iconDnDAudioMulti.tiff \
Images/iconAudioCDSm.tiff \
Images/iconAudioCD.tiff \
Images/iconCD.tiff \
Images/iconCDR.tiff \
Images/iconCDRW.tiff \
Images/iconMultiSelection.tiff \
Images/iconGeneral.tiff \
Images/iconFileBurn.tiff \
Images/iconFileIso.tiff \
Images/iconFileCdr.tiff \
Images/iconAddFiles.tiff \
Images/iconAddAudioTracks.tiff \
Images/iconRemoveTracks.tiff \
Resources/Console.gorm \
Resources/Readme.gorm \
Resources/ToolPanel.gorm \
Resources/BlankPanel.gorm \
Resources/PreferencesWindow.gorm \
Resources/ParametersWindow.gorm \
Resources/BurnProgress.gorm \
Resources/WorkInProgress.gorm \
Resources/ProjectWindow.gorm \
Resources/MediaInspector.gorm \
Resources/AudioCDInspector.gorm \
README

#
# Header files
#

Burn_HEADERS= \
AppController.h \
ConsolePanel.h \
Constants.h \
ProjectWindowController.h \
PreferencesWindowController.h \
ParametersWindowController.h \
Project.h \
Track.h \
Functions.h \
ExtProgressIndicator.h \
ExtendedOutlineView.h \
BurnProgressController.h \
BurnCDHelper.h \
CreateISOHelper.h \
ConvertAudioHelper.h \
ReadmePanel.h \
ToolPanel.h \
ToolSelector.h \
Inspectors/InspectorsWin.h \
Inspectors/TrackInspector.h  \
Inspectors/MediaInspector.h \
Inspectors/AudioCDInspector.h \
BlankPanel.h \
OpenISOImagePanel.h \
GeneralParameters.h \
GeneralPrefs.h \
WorkInProgress.h

#
# Class files
#

Burn_OBJC_FILES= \
main.m \
AppController.m \
ConsolePanel.m \
Constants.m \
ProjectWindowController.m \
ProjectWindowController+DnD.m \
ProjectWindowController+OlvDelegate.m \
PreferencesWindowController.m \
ParametersWindowController.m \
Project.m \
Project+Audio.m \
Project+Data.m \
Track.m \
Functions.m \
ExtProgressIndicator.m \
ExtendedOutlineView.m \
BurnProgressController.m \
BurnCDHelper.m \
CreateISOHelper.m \
ConvertAudioHelper.m \
ReadmePanel.m \
ToolPanel.m \
ToolSelector.m \
Inspectors/InspectorsWin.m \
Inspectors/TrackInspector.m  \
Inspectors/MediaInspector.m \
Inspectors/AudioCDInspector.m \
BlankPanel.m \
OpenISOImagePanel.m \
GeneralParameters.m \
GeneralPrefs.m \
WorkInProgress.m

#
# C files
#

Burn_C_FILES= 

Burn_PRINCIPAL_CLASS = AppController

Burn_LANGUAGES=English German French
Burn_LOCALIZED_RESOURCE_FILES = \
	GeneralParams.gorm \
	GeneralPrefs.gorm \
	Localizable.strings \
	TrackInspector.gorm


-include GNUmakefile.preamble
-include GNUmakefile.local
include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/application.make

# Only build the doc if doc=yes was passed on the command line
ifeq ($(doc),yes)
include $(GNUSTEP_MAKEFILES)/documentation.make
endif

-include GNUmakefile.postamble
